# Generated by Django 3.2.5 on 2021-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Users/jacklewis/Documents/work/python-projects/ml-api/portfolio/blog/milky-way.jpeg', upload_to='blogphotos/'),
        ),
    ]
