# Generated by Django 3.2.5 on 2021-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Users/jacklewis/Documents/work/python-projects/ml-api/portfolio/media/images/milky-way.jpeg', upload_to='images/'),
        ),
    ]
