# Generated by Django 3.2.5 on 2021-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210822_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github',
            field=models.TextField(default='https://www.https://github.com/jacknlewis', max_length=255),
            preserve_default=False,
        ),
    ]
